import { hashPassword } from './auth.js';
import { db } from './db.js';
import type { Category, Country, Station, SubscriptionPlan, User } from './types.js';

export function runSeed() {
  db.seedInitialData((data) => {
    console.log('Seeding Christian Radios initial database...');

    // 1. Subscription Plans
    const plans: SubscriptionPlan[] = [
      {
        id: 'plan_free',
        name: 'Free Directory',
        tier: 'FREE',
        description: 'Basic listing for registered non-profit Christian radio stations.',
        monthlyPriceTzs: 0,
        annualPriceTzs: 0,
        monthlyPriceUsd: 0,
        annualPriceUsd: 0,
        currency: 'TZS',
        maxStations: 1,
        analyticsAccessLevel: 'BASIC',
        featuredIncluded: false,
        streamMonitoringIntervalMinutes: 30,
        customBranding: false,
        prioritySupport: false,
        isActive: true,
      },
      {
        id: 'plan_starter',
        name: 'Starter Broadcaster',
        tier: 'STARTER',
        description: 'Ideal for local and community Christian broadcasters looking to grow.',
        monthlyPriceTzs: 35000,
        annualPriceTzs: 350000,
        monthlyPriceUsd: 15,
        annualPriceUsd: 150,
        currency: 'TZS',
        maxStations: 2,
        analyticsAccessLevel: 'ADVANCED',
        featuredIncluded: false,
        streamMonitoringIntervalMinutes: 15,
        customBranding: true,
        prioritySupport: false,
        isActive: true,
      },
      {
        id: 'plan_professional',
        name: 'Professional Radio Network',
        tier: 'PROFESSIONAL',
        description: 'Advanced analytics, fast stream monitoring, and featured search placement.',
        monthlyPriceTzs: 85000,
        annualPriceTzs: 850000,
        monthlyPriceUsd: 35,
        annualPriceUsd: 350,
        currency: 'TZS',
        maxStations: 5,
        analyticsAccessLevel: 'ADVANCED',
        featuredIncluded: true,
        streamMonitoringIntervalMinutes: 5,
        customBranding: true,
        prioritySupport: true,
        isActive: true,
      },
      {
        id: 'plan_business',
        name: 'Enterprise Broadcast Network',
        tier: 'BUSINESS',
        description: 'Multi-station syndicate with real-time 1-minute telemetry and homepage placements.',
        monthlyPriceTzs: 195000,
        annualPriceTzs: 1950000,
        monthlyPriceUsd: 80,
        annualPriceUsd: 800,
        currency: 'TZS',
        maxStations: 15,
        analyticsAccessLevel: 'FULL_ENTERPRISE',
        featuredIncluded: true,
        streamMonitoringIntervalMinutes: 1,
        customBranding: true,
        prioritySupport: true,
        isActive: true,
      },
    ];
    data.plans = plans;

    // 2. Categories
    const categories: Category[] = [
      {
        id: 'cat_gospel',
        name: 'Gospel Music',
        slug: 'gospel-music',
        iconName: 'Disc',
        description: 'Uplifting African and International Gospel music and artists.',
        displayOrder: 1,
        isActive: true,
      },
      {
        id: 'cat_worship',
        name: 'Praise & Worship',
        slug: 'praise-worship',
        iconName: 'Heart',
        description: '24/7 non-stop heartfelt praise, worship anthems, and adoration.',
        displayOrder: 2,
        isActive: true,
      },
      {
        id: 'cat_teaching',
        name: 'Bible Teaching & Sermons',
        slug: 'bible-teaching',
        iconName: 'BookOpen',
        description: 'Expository Bible sermons, verses study, and Christian theology.',
        displayOrder: 3,
        isActive: true,
      },
      {
        id: 'cat_talk',
        name: 'Christian Talk & News',
        slug: 'christian-talk',
        iconName: 'Radio',
        description: 'Christian worldview discussions, family counseling, and global faith news.',
        displayOrder: 4,
        isActive: true,
      },
      {
        id: 'cat_prayer',
        name: 'Prayer & Intercession',
        slug: 'prayer-intercession',
        iconName: 'Flame',
        description: 'Live morning prayer altars, deliverance, and continuous intercession.',
        displayOrder: 5,
        isActive: true,
      },
      {
        id: 'cat_youth',
        name: 'Youth & Contemporary',
        slug: 'youth-contemporary',
        iconName: 'Sparkles',
        description: 'Christian hip-hop, contemporary Christian hits, and young adult programs.',
        displayOrder: 6,
        isActive: true,
      },
      {
        id: 'cat_hymns',
        name: 'Hymns & Traditional',
        slug: 'hymns-traditional',
        iconName: 'Music',
        description: 'Classical church hymns, choral music, and liturgical chants.',
        displayOrder: 7,
        isActive: true,
      },
      {
        id: 'cat_family',
        name: 'Family & Kids',
        slug: 'family-kids',
        iconName: 'Users',
        description: 'Biblical stories, moral dramas, marriage enrichment, and kids programming.',
        displayOrder: 8,
        isActive: true,
      },
    ];
    data.categories = categories;

    // 3. Countries
    const countries: Country[] = [
      {
        code: 'TZ',
        name: 'Tanzania',
        flagEmoji: '🇹🇿',
        continent: 'Africa',
        isFeatured: true,
      },
      {
        code: 'KE',
        name: 'Kenya',
        flagEmoji: '🇰🇪',
        continent: 'Africa',
        isFeatured: true,
      },
      {
        code: 'UG',
        name: 'Uganda',
        flagEmoji: '🇺🇬',
        continent: 'Africa',
        isFeatured: true,
      },
      {
        code: 'US',
        name: 'United States',
        flagEmoji: '🇺🇸',
        continent: 'North America',
        isFeatured: true,
      },
      {
        code: 'GB',
        name: 'United Kingdom',
        flagEmoji: '🇬🇧',
        continent: 'Europe',
        isFeatured: true,
      },
      {
        code: 'NG',
        name: 'Nigeria',
        flagEmoji: '🇳🇬',
        continent: 'Africa',
        isFeatured: true,
      },
      {
        code: 'ZA',
        name: 'South Africa',
        flagEmoji: '🇿🇦',
        continent: 'Africa',
        isFeatured: true,
      },
      {
        code: 'GH',
        name: 'Ghana',
        flagEmoji: '🇬🇭',
        continent: 'Africa',
        isFeatured: true,
      },
      {
        code: 'RW',
        name: 'Rwanda',
        flagEmoji: '🇷🇼',
        continent: 'Africa',
        isFeatured: true,
      },
      {
        code: 'ZM',
        name: 'Zambia',
        flagEmoji: '🇿🇲',
        continent: 'Africa',
        isFeatured: false,
      },
      {
        code: 'MW',
        name: 'Malawi',
        flagEmoji: '🇲🇼',
        continent: 'Africa',
        isFeatured: false,
      },
      {
        code: 'BR',
        name: 'Brazil',
        flagEmoji: '🇧🇷',
        continent: 'South America',
        isFeatured: false,
      },
      {
        code: 'CA',
        name: 'Canada',
        flagEmoji: '🇨🇦',
        continent: 'North America',
        isFeatured: false,
      },
      {
        code: 'AU',
        name: 'Australia',
        flagEmoji: '🇦🇺',
        continent: 'Oceania',
        isFeatured: false,
      },
    ];
    data.countries = countries;

    // 4. Seed Users
    const adminUser: User = {
      id: 'usr_admin_01',
      email: 'admin@christianradios.org',
      passwordHash: hashPassword('Admin@2026!'),
      role: 'SUPER_ADMIN',
      name: 'Dr. David Mwangi',
      emailVerified: true,
      phone: '+255 700 123 456',
      status: 'ACTIVE',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const opsUser: User = {
      id: 'usr_ops_01',
      email: 'ops@christianradios.org',
      passwordHash: hashPassword('Ops@2026!'),
      role: 'OPERATIONS_ADMIN',
      name: 'Grace Mlay',
      emailVerified: true,
      status: 'ACTIVE',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const financeUser: User = {
      id: 'usr_fin_01',
      email: 'finance@christianradios.org',
      passwordHash: hashPassword('Finance@2026!'),
      role: 'FINANCE_ADMIN',
      name: 'Emanuel Kimaro',
      emailVerified: true,
      status: 'ACTIVE',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const ownerUser1: User = {
      id: 'usr_owner_01',
      email: 'owner@radiomaria.tz',
      passwordHash: hashPassword('Owner@2026!'),
      role: 'RADIO_OWNER',
      name: 'Fr. Telesphore Kabula',
      emailVerified: true,
      phone: '+255 754 889 900',
      status: 'ACTIVE',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const ownerUser2: User = {
      id: 'usr_owner_02',
      email: 'manager@upendofm.tz',
      passwordHash: hashPassword('Owner@2026!'),
      role: 'RADIO_OWNER',
      name: 'Bishop Alex Malasusa',
      emailVerified: true,
      phone: '+255 713 555 777',
      status: 'ACTIVE',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const listenerUser: User = {
      id: 'usr_listener_01',
      email: 'listener@christianradios.org',
      passwordHash: hashPassword('Listener@2026!'),
      role: 'LISTENER',
      name: 'Sarah Johnson',
      emailVerified: true,
      status: 'ACTIVE',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    data.users = [adminUser, opsUser, financeUser, ownerUser1, ownerUser2, listenerUser];

    // 5. Radio Owner Profiles
    data.ownerProfiles = [
      {
        id: 'prof_owner_01',
        userId: ownerUser1.id,
        organizationName: 'Radio Maria Tanzania Association',
        phone: '+255 754 889 900',
        country: 'Tanzania',
        bio: 'Broadcasting Catholic prayers, gospel music, and family education across Tanzania since 1996.',
        verified: true,
        website: 'https://www.radiomaria.co.tz',
      },
      {
        id: 'prof_owner_02',
        userId: ownerUser2.id,
        organizationName: 'Evangelical Lutheran Church in Tanzania (ELCT)',
        phone: '+255 713 555 777',
        country: 'Tanzania',
        bio: 'Upendo FM — Sauti ya Tumaini na Faraja. Reaching East Africa with uplifting gospel melodies.',
        verified: true,
        website: 'https://www.upendofm.co.tz',
      },
    ];

    // 6. Subscriptions
    const sub1 = {
      id: 'sub_owner_01',
      ownerId: ownerUser1.id,
      planId: 'plan_professional',
      status: 'ACTIVE' as const,
      billingInterval: 'MONTHLY' as const,
      currentPeriodStart: new Date(Date.now() - 10 * 86400000).toISOString(),
      currentPeriodEnd: new Date(Date.now() + 20 * 86400000).toISOString(),
      cancelAtPeriodEnd: false,
      autoRenew: true,
      createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const sub2 = {
      id: 'sub_owner_02',
      ownerId: ownerUser2.id,
      planId: 'plan_starter',
      status: 'ACTIVE' as const,
      billingInterval: 'MONTHLY' as const,
      currentPeriodStart: new Date(Date.now() - 5 * 86400000).toISOString(),
      currentPeriodEnd: new Date(Date.now() + 25 * 86400000).toISOString(),
      cancelAtPeriodEnd: false,
      autoRenew: true,
      createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
      updatedAt: new Date().toISOString(),
    };

    data.subscriptions = [sub1, sub2];

    // 7. Seed Stations
    const stations: Station[] = [
      {
        id: 'stn_radio_maria_tz',
        ownerId: ownerUser1.id,
        name: 'Radio Maria Tanzania',
        slug: 'radio-maria-tanzania',
        tagline: 'Sauti ya Kikristo Nyumbani Mwako',
        description: 'Radio Maria Tanzania ni kituo cha utangazaji cha Kanisa Katoliki kinachorusha matangazo ya kiroho, maombi ya Rozari, tafakari ya Neno la Mungu, na nyimbo za kwaya na injili.',
        logoUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&auto=format&fit=crop&q=80',
        countryCode: 'TZ',
        region: 'Dar es Salaam',
        city: 'Dar es Salaam',
        language: 'Swahili',
        genre: 'Catholic Prayers & Gospel',
        categoryId: 'cat_prayer',
        denomination: 'Catholic',
        websiteUrl: 'https://www.radiomaria.co.tz',
        email: 'info@radiomaria.co.tz',
        phone: '+255 22 277 5588',
        socialLinks: {
          facebook: 'https://facebook.com/radiomariatz',
          youtube: 'https://youtube.com/@radiomariatz',
        },
        streamUrl: 'https://dreamsiteradiocp5.com/proxy/rmtz?mp=/stream',
        backupStreamUrl: 'https://stream.radiomaria.co.tz/live.mp3',
        streamType: 'MP3',
        bitrateKbps: 128,
        timezone: 'Africa/Dar_es_Salaam',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: true,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        lastOnlineAt: new Date().toISOString(),
        responseLatencyMs: 142,
        playCount: 14820,
        favoriteCount: 1240,
        currentListenersCount: 382,
        createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
        schedule: [
          { dayOfWeek: 0, startTime: '06:00', endTime: '08:00', programName: 'Misa Takatifu Asubuhi', presenter: 'Fr. Telesphore' },
          { dayOfWeek: 0, startTime: '12:00', endTime: '13:00', programName: 'Sala ya Malaika wa Bwana & Rozari', presenter: 'Kwaya ya Watakatifu' },
          { dayOfWeek: 1, startTime: '05:30', endTime: '07:00', programName: 'Kiamsha Kiroho', presenter: 'Regina Mmari' },
          { dayOfWeek: 1, startTime: '20:00', endTime: '22:00', programName: 'Usiku wa Neema na Maombezi', presenter: 'Padre Joseph' },
        ],
      },
      {
        id: 'stn_upendo_fm',
        ownerId: ownerUser2.id,
        name: 'Upendo FM 107.7',
        slug: 'upendo-fm-tanzania',
        tagline: 'Sauti ya Tumaini na Faraja',
        description: 'Upendo FM 107.7 Dar es Salaam ni radio ya Kiinjili ya Kilutheri inayohubiri habari njema za wokovu kupitia nyimbo za injili, mafundisho ya familia na maombi.',
        logoUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80',
        countryCode: 'TZ',
        region: 'Dar es Salaam',
        city: 'Dar es Salaam',
        language: 'Swahili',
        genre: 'Gospel & Praise',
        categoryId: 'cat_gospel',
        denomination: 'Lutheran (ELCT)',
        websiteUrl: 'https://www.upendofm.co.tz',
        email: 'info@upendofm.co.tz',
        phone: '+255 22 211 0033',
        streamUrl: 'https://stream.zeno.fm/upendofm',
        streamType: 'MP3',
        bitrateKbps: 128,
        timezone: 'Africa/Dar_es_Salaam',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: true,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        lastOnlineAt: new Date().toISOString(),
        responseLatencyMs: 165,
        playCount: 11450,
        favoriteCount: 890,
        currentListenersCount: 245,
        createdAt: new Date(Date.now() - 80 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'stn_wapo_radio',
        ownerId: ownerUser1.id,
        name: 'WAPO Radio FM 98.0',
        slug: 'wapo-radio-fm',
        tagline: 'Kimbilio Lako la Kiroho',
        description: 'WAPO Radio ni redio ya Kikristo ya Kikanisa inayosikika Dar es Salaam, Pwani na Zanzibar ikieneza Neno la Mungu kwa uaminifu na nyimbo za sifa.',
        logoUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&auto=format&fit=crop&q=80',
        countryCode: 'TZ',
        region: 'Dar es Salaam',
        city: 'Dar es Salaam',
        language: 'Swahili',
        genre: 'Bible Teaching & Praise',
        categoryId: 'cat_teaching',
        denomination: 'Pentecostal',
        websiteUrl: 'https://waporadio.co.tz',
        streamUrl: 'https://stream.zeno.fm/waporadio',
        streamType: 'MP3',
        bitrateKbps: 128,
        timezone: 'Africa/Dar_es_Salaam',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: true,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        lastOnlineAt: new Date().toISOString(),
        responseLatencyMs: 180,
        playCount: 9230,
        favoriteCount: 710,
        currentListenersCount: 195,
        createdAt: new Date(Date.now() - 75 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'stn_safina_fm',
        ownerId: ownerUser2.id,
        name: 'Radio Safina 92.6 FM',
        slug: 'radio-safina-arusha',
        tagline: 'Safina ya Wokovu na Tumaini',
        description: 'Kituo cha utangazaji cha Kikristo kutoka Mlima Meru, Arusha Tanzania. Kinatoa nyimbo za kwaya, mafundisho ya vijana, na matangazo ya amani.',
        logoUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=80',
        countryCode: 'TZ',
        region: 'Arusha',
        city: 'Arusha',
        language: 'Swahili',
        genre: 'Youth Gospel & Talk',
        categoryId: 'cat_youth',
        denomination: 'Non-denominational',
        streamUrl: 'https://stream.zeno.fm/safinafm',
        streamType: 'MP3',
        bitrateKbps: 128,
        timezone: 'Africa/Dar_es_Salaam',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: false,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        playCount: 7420,
        favoriteCount: 520,
        currentListenersCount: 120,
        createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'stn_praise_fm_mbeya',
        ownerId: ownerUser1.id,
        name: 'Praise FM 99.3',
        slug: 'praise-fm-mbeya',
        tagline: 'Sifa Zote kwa Yesu Kristo',
        description: 'Inayosikika nyanda za juu kusini Mbeya, Songwe, na Ruvuma. Kituo chenye nguvu ya maombi, uponyaji na sifa za kiwango cha juu.',
        logoUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=80',
        countryCode: 'TZ',
        region: 'Mbeya',
        city: 'Mbeya',
        language: 'Swahili',
        genre: 'Praise & Worship',
        categoryId: 'cat_worship',
        denomination: 'Evangelical',
        streamUrl: 'https://stream.zeno.fm/praisefmmbeya',
        streamType: 'MP3',
        bitrateKbps: 96,
        timezone: 'Africa/Dar_es_Salaam',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: false,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        playCount: 5310,
        favoriteCount: 430,
        createdAt: new Date(Date.now() - 50 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'stn_hope_fm_kenya',
        ownerId: ownerUser1.id,
        name: 'Hope FM 93.3',
        slug: 'hope-fm-nairobi',
        tagline: 'Listen and Live',
        description: 'The premier Christian radio station in Kenya, operated by CITAM. Inspiring millions with biblical truth, wholesome music, and family shows.',
        logoUrl: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1200&auto=format&fit=crop&q=80',
        countryCode: 'KE',
        region: 'Nairobi',
        city: 'Nairobi',
        language: 'English & Swahili',
        genre: 'Contemporary Christian Music',
        categoryId: 'cat_worship',
        denomination: 'Pentecostal',
        websiteUrl: 'https://hopefm.org',
        streamUrl: 'https://streaming.shoutcast.com/hope-fm-kenya',
        streamType: 'MP3',
        bitrateKbps: 128,
        timezone: 'Africa/Nairobi',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: true,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        playCount: 16200,
        favoriteCount: 1390,
        currentListenersCount: 410,
        createdAt: new Date(Date.now() - 100 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'stn_premier_christian_uk',
        ownerId: ownerUser1.id,
        name: 'Premier Christian Radio',
        slug: 'premier-christian-radio-uk',
        tagline: 'Faith, Hope and Life for the Nation',
        description: 'The UK’s leading Christian broadcaster. Engaging news from a faith perspective, biblical discussions, inspiring worship, and interviews.',
        logoUrl: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=1200&auto=format&fit=crop&q=80',
        countryCode: 'GB',
        region: 'England',
        city: 'London',
        language: 'English',
        genre: 'Christian Talk & Worship',
        categoryId: 'cat_talk',
        denomination: 'Non-denominational',
        websiteUrl: 'https://www.premierchristianradio.com',
        streamUrl: 'https://media-the.musicradio.com/PremierChristianRadio',
        streamType: 'MP3',
        bitrateKbps: 128,
        timezone: 'Europe/London',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: true,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        playCount: 18900,
        favoriteCount: 1650,
        currentListenersCount: 520,
        createdAt: new Date(Date.now() - 110 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'stn_moody_radio_us',
        ownerId: ownerUser1.id,
        name: 'Moody Radio Network',
        slug: 'moody-radio-network',
        tagline: 'From the Word to Life',
        description: 'Trustworthy biblical teaching, warm Christian fellowship, and sacred worship broadcasting from Chicago since 1926.',
        logoUrl: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&auto=format&fit=crop&q=80',
        countryCode: 'US',
        region: 'Illinois',
        city: 'Chicago',
        language: 'English',
        genre: 'Bible Teaching & Sermons',
        categoryId: 'cat_teaching',
        denomination: 'Evangelical',
        websiteUrl: 'https://www.moodyradio.org',
        streamUrl: 'https://primary.moodyradio.org/live/wmbi/icecast.audio',
        streamType: 'ICECAST',
        bitrateKbps: 128,
        timezone: 'America/Chicago',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: true,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        playCount: 24300,
        favoriteCount: 2100,
        currentListenersCount: 680,
        createdAt: new Date(Date.now() - 120 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'stn_klove_us',
        ownerId: ownerUser1.id,
        name: 'K-LOVE Radio',
        slug: 'k-love-contemporary',
        tagline: 'Positive, Encouraging K-LOVE',
        description: 'Uplifting contemporary Christian music featuring Lauren Daigle, Chris Tomlin, Phil Wickham, TobyMac and more.',
        logoUrl: 'https://images.unsplash.com/photo-1447069387593-a5de0862481e?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80',
        countryCode: 'US',
        region: 'California',
        city: 'Rocklin',
        language: 'English',
        genre: 'Contemporary Christian Music',
        categoryId: 'cat_worship',
        denomination: 'Non-denominational',
        websiteUrl: 'https://www.klove.com',
        streamUrl: 'https://listen.klove.com/stream',
        streamType: 'MP3',
        bitrateKbps: 128,
        timezone: 'America/Los_Angeles',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: true,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        playCount: 31200,
        favoriteCount: 2840,
        currentListenersCount: 890,
        createdAt: new Date(Date.now() - 130 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'stn_cbn_praise',
        ownerId: ownerUser1.id,
        name: 'CBN Praise Radio',
        slug: 'cbn-praise-radio',
        tagline: 'Continuous Praise & Healing Music',
        description: '24/7 global worship streams from the Christian Broadcasting Network. Instrumental hymns and modern praise.',
        logoUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80',
        countryCode: 'US',
        region: 'Virginia',
        city: 'Virginia Beach',
        language: 'English',
        genre: 'Praise & Worship',
        categoryId: 'cat_worship',
        denomination: 'Evangelical',
        websiteUrl: 'https://www.cbn.com/radio',
        streamUrl: 'https://stream.zeno.fm/cbnpraise',
        streamType: 'MP3',
        bitrateKbps: 128,
        timezone: 'America/New_York',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: false,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        playCount: 8900,
        favoriteCount: 640,
        createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'stn_habari_maalum',
        ownerId: ownerUser2.id,
        name: 'Habari Maalum FM 97.7',
        slug: 'habari-maalum-arusha',
        tagline: 'Habari Njema kwa Watu Wote',
        description: 'Kituo kikuu cha utangazaji cha Kikristo kutoka Njiro Arusha. Kinatoa mafundisho ya Neno la Mungu, muziki wa kwaya, michezo ya watoto na habari za amani.',
        logoUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&auto=format&fit=crop&q=80',
        countryCode: 'TZ',
        region: 'Arusha',
        city: 'Arusha',
        language: 'Swahili',
        genre: 'Bible Teaching & Sermons',
        categoryId: 'cat_teaching',
        denomination: 'Pentecostal',
        websiteUrl: 'https://habarimaalum.org',
        email: 'info@habarimaalum.org',
        phone: '+255 27 254 8000',
        streamUrl: 'https://stream.zeno.fm/habarimaalum',
        streamType: 'MP3',
        bitrateKbps: 128,
        timezone: 'Africa/Dar_es_Salaam',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: true,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        playCount: 13400,
        favoriteCount: 1120,
        currentListenersCount: 310,
        createdAt: new Date(Date.now() - 70 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'stn_power_fm_ug',
        ownerId: ownerUser1.id,
        name: 'Power FM 104.1',
        slug: 'power-fm-kampala',
        tagline: 'It is All About Love and Jesus',
        description: 'Uganda’s premier contemporary Christian radio station broadcasting high energy urban gospel, inspiring talk shows, and life-changing ministry from Kampala.',
        logoUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&auto=format&fit=crop&q=80',
        countryCode: 'UG',
        region: 'Central',
        city: 'Kampala',
        language: 'English & Luganda',
        genre: 'Youth & Contemporary',
        categoryId: 'cat_youth',
        denomination: 'Pentecostal',
        websiteUrl: 'https://powerfm.ug',
        email: 'info@powerfm.ug',
        phone: '+256 414 250 104',
        streamUrl: 'https://stream.zeno.fm/powerfmug',
        streamType: 'MP3',
        bitrateKbps: 128,
        timezone: 'Africa/Kampala',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: true,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        playCount: 14900,
        favoriteCount: 1280,
        currentListenersCount: 340,
        createdAt: new Date(Date.now() - 85 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'stn_maria_rwanda',
        ownerId: ownerUser1.id,
        name: 'Radio Maria Rwanda 97.3',
        slug: 'radio-maria-rwanda',
        tagline: 'Ijwi ry’Ubukristu mu Rugo rwawe',
        description: 'Radio Maria Rwanda broadcasts continuous Catholic rosary prayers, daily holy mass from Kigali, theological discussions, and peaceful choral worship across Rwanda.',
        logoUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80',
        countryCode: 'RW',
        region: 'Kigali',
        city: 'Kigali',
        language: 'Kinyarwanda & French',
        genre: 'Prayer & Intercession',
        categoryId: 'cat_prayer',
        denomination: 'Catholic',
        websiteUrl: 'https://www.radiomaria.rw',
        streamUrl: 'https://stream.radiomaria.rw/live.mp3',
        streamType: 'MP3',
        bitrateKbps: 128,
        timezone: 'Africa/Kigali',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: true,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        playCount: 9800,
        favoriteCount: 780,
        currentListenersCount: 220,
        createdAt: new Date(Date.now() - 65 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'stn_wig_radio_ng',
        ownerId: ownerUser1.id,
        name: 'WiGRadio Nigeria',
        slug: 'wig-radio-nigeria',
        tagline: 'Reaching the World with Good News',
        description: 'Dynamic Nigerian online gospel station featuring vibrant African praise, fiery evangelical sermons, youth empowerment, and live campus fellowships.',
        logoUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&auto=format&fit=crop&q=80',
        countryCode: 'NG',
        region: 'Lagos',
        city: 'Lagos',
        language: 'English & Yoruba',
        genre: 'Gospel Music',
        categoryId: 'cat_gospel',
        denomination: 'Pentecostal',
        websiteUrl: 'https://wigradio.com',
        streamUrl: 'https://stream.zeno.fm/wigradio',
        streamType: 'MP3',
        bitrateKbps: 128,
        timezone: 'Africa/Lagos',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: true,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        playCount: 17200,
        favoriteCount: 1450,
        currentListenersCount: 430,
        createdAt: new Date(Date.now() - 95 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'stn_ccfm_sa',
        ownerId: ownerUser1.id,
        name: 'CCFM 107.5 Cape Town',
        slug: 'ccfm-cape-town',
        tagline: 'Changing Lives for Good',
        description: 'Cape Community FM (CCFM) is South Africa’s leading community Christian radio station broadcasting family-friendly music, uplifting talk, and community care.',
        logoUrl: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1200&auto=format&fit=crop&q=80',
        countryCode: 'ZA',
        region: 'Western Cape',
        city: 'Cape Town',
        language: 'English & Afrikaans',
        genre: 'Christian Talk & News',
        categoryId: 'cat_talk',
        denomination: 'Non-denominational',
        websiteUrl: 'https://www.ccfm.org.za',
        streamUrl: 'https://stream.zeno.fm/ccfmcapetown',
        streamType: 'MP3',
        bitrateKbps: 128,
        timezone: 'Africa/Johannesburg',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: true,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        playCount: 12100,
        favoriteCount: 990,
        currentListenersCount: 280,
        createdAt: new Date(Date.now() - 80 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'stn_sunny_fm_gh',
        ownerId: ownerUser2.id,
        name: 'Sunny FM 88.7 Accra',
        slug: 'sunny-fm-ghana',
        tagline: 'The Better Way to Start Your Day',
        description: 'Ghana’s favourite Christian music station playing soothing African and global praise, scripture meditations, and family relationship talks.',
        logoUrl: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=1200&auto=format&fit=crop&q=80',
        countryCode: 'GH',
        region: 'Greater Accra',
        city: 'Accra',
        language: 'English & Twi',
        genre: 'Praise & Worship',
        categoryId: 'cat_worship',
        denomination: 'Non-denominational',
        websiteUrl: 'https://sunnyfmonline.com',
        streamUrl: 'https://stream.zeno.fm/sunnyfmaccra',
        streamType: 'MP3',
        bitrateKbps: 128,
        timezone: 'Africa/Accra',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: false,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        playCount: 10500,
        favoriteCount: 820,
        currentListenersCount: 230,
        createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'stn_ucb1_uk',
        ownerId: ownerUser1.id,
        name: 'UCB 1 United Christian Broadcasters',
        slug: 'ucb-1-radio-uk',
        tagline: 'Life-changing Radio for the UK and Beyond',
        description: 'UCB 1 is the national Christian radio station of the UK broadcasting encouraging music, Word for Today devotionals, and inspiring personal faith stories.',
        logoUrl: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=400&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80',
        countryCode: 'GB',
        region: 'Staffordshire',
        city: 'Stoke-on-Trent',
        language: 'English',
        genre: 'Contemporary Christian Music',
        categoryId: 'cat_worship',
        denomination: 'Evangelical',
        websiteUrl: 'https://www.ucb.co.uk',
        streamUrl: 'https://stream.zeno.fm/ucb1uk',
        streamType: 'MP3',
        bitrateKbps: 128,
        timezone: 'Europe/London',
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED',
        isFeatured: true,
        streamStatus: 'ONLINE',
        lastCheckedAt: new Date().toISOString(),
        playCount: 15600,
        favoriteCount: 1320,
        currentListenersCount: 460,
        createdAt: new Date(Date.now() - 105 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ];

    data.stations = stations;

    // 8. Sample Payments & Invoices
    const pay1 = {
      id: 'pay_001',
      trackingId: 'PESA_TZ_20260901_99182',
      ownerId: ownerUser1.id,
      subscriptionId: sub1.id,
      amount: 85000,
      currency: 'TZS',
      status: 'COMPLETED' as const,
      provider: 'PESAPAL' as const,
      providerRef: 'PP_REF_8819284',
      paymentMethod: 'MPESA' as const,
      description: 'Professional Radio Network Plan - Monthly',
      createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
      completedAt: new Date(Date.now() - 10 * 86400000 + 45000).toISOString(),
    };

    const pay2 = {
      id: 'pay_002',
      trackingId: 'PESA_TZ_20260901_33211',
      ownerId: ownerUser2.id,
      subscriptionId: sub2.id,
      amount: 35000,
      currency: 'TZS',
      status: 'COMPLETED' as const,
      provider: 'PESAPAL' as const,
      providerRef: 'PP_REF_1102938',
      paymentMethod: 'TIGO_PESA' as const,
      description: 'Starter Broadcaster Plan - Monthly',
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
      completedAt: new Date(Date.now() - 5 * 86400000 + 30000).toISOString(),
    };

    data.payments = [pay1, pay2];

    data.invoices = [
      {
        id: 'inv_2026_001',
        invoiceNumber: 'CR-INV-2026-0001',
        ownerId: ownerUser1.id,
        paymentId: pay1.id,
        subscriptionId: sub1.id,
        amount: 85000,
        currency: 'TZS',
        taxAmount: 0,
        billingPeriod: '1 Month (Professional)',
        status: 'PAID',
        issuedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
        planName: 'Professional Radio Network',
      },
      {
        id: 'inv_2026_002',
        invoiceNumber: 'CR-INV-2026-0002',
        ownerId: ownerUser2.id,
        paymentId: pay2.id,
        subscriptionId: sub2.id,
        amount: 35000,
        currency: 'TZS',
        taxAmount: 0,
        billingPeriod: '1 Month (Starter)',
        status: 'PAID',
        issuedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
        planName: 'Starter Broadcaster',
      },
    ];

    // 9. Featured Campaigns
    data.featuredCampaigns = [
      {
        id: 'camp_001',
        stationId: 'stn_radio_maria_tz',
        ownerId: ownerUser1.id,
        placement: 'HOMEPAGE_HERO',
        startDate: new Date(Date.now() - 5 * 86400000).toISOString(),
        endDate: new Date(Date.now() + 25 * 86400000).toISOString(),
        price: 50000,
        currency: 'TZS',
        paymentId: pay1.id,
        status: 'ACTIVE',
        impressions: 4820,
        clicks: 612,
        createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
      },
    ];

    // 10. Advertisements
    data.advertisements = [
      {
        id: 'ad_001',
        title: 'Tanzania National Gospel Conference 2026',
        placement: 'BANNER_TOP',
        imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80',
        targetUrl: 'https://christianradios.org',
        sponsorName: 'Tanzania Gospel Music Association',
        startDate: new Date(Date.now() - 10 * 86400000).toISOString(),
        endDate: new Date(Date.now() + 20 * 86400000).toISOString(),
        status: 'ACTIVE',
        impressions: 8930,
        clicks: 432,
        createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
      },
    ];

    // 11. Sample Support Tickets
    data.supportTickets = [
      {
        id: 'tkt_001',
        ownerId: ownerUser1.id,
        subject: 'Assistance with SSL Shoutcast backup stream URL',
        category: 'Technical Stream Setup',
        message: 'Hello Support, we are configuring a secondary Shoutcast v2 stream with TLS port 8443 and would like to verify if your player supports auto-fallback.',
        priority: 'MEDIUM',
        status: 'RESOLVED',
        responses: [
          {
            id: 'resp_01',
            authorId: adminUser.id,
            authorName: 'Support Agent Emanuel',
            authorRole: 'SUPPORT_AGENT',
            message: 'Hello Father Telesphore. Yes, Christian Radios player automatically switches to your configured backup stream within 2.5 seconds if the primary endpoint is unreachable.',
            timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
          },
        ],
        createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
    ];

    // 12. Audit Logs
    data.auditLogs = [
      {
        id: 'audit_init_01',
        actorId: adminUser.id,
        actorEmail: adminUser.email,
        actorRole: 'SUPER_ADMIN',
        action: 'PLATFORM_INITIALIZED',
        entityType: 'PlatformSettings',
        entityId: 'settings',
        details: 'Initial platform bootstrap and directory verification completed.',
        ipAddress: '127.0.0.1',
        timestamp: new Date().toISOString(),
      },
      {
        id: 'audit_init_02',
        actorId: adminUser.id,
        actorEmail: adminUser.email,
        actorRole: 'SUPER_ADMIN',
        action: 'STATION_APPROVED',
        entityType: 'Station',
        entityId: 'stn_radio_maria_tz',
        details: 'Verified broadcast license and activated Radio Maria Tanzania.',
        ipAddress: '127.0.0.1',
        timestamp: new Date().toISOString(),
      },
    ];

    // 13. Prayer Requests
    data.prayerRequests = [
      {
        id: 'pray_001',
        authorName: 'Grace Mwenda',
        isAnonymous: false,
        category: 'Healing',
        title: 'Healing for My Mother (High Blood Pressure & Diabetes)',
        prayerPoints: 'Please stand in prayer with my family for my mother who is undergoing medical treatment in Arusha. We believe by His stripes she is healed.',
        prayedCount: 48,
        stationId: 'stn_radio_maria_tz',
        stationName: 'Radio Maria Tanzania',
        countryCode: 'TZ',
        status: 'APPROVED',
        createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'pray_002',
        authorName: 'Anonymous Listener',
        isAnonymous: true,
        category: 'Financial',
        title: 'Employment & Financial Breakthrough',
        prayerPoints: 'I graduated last year and have been searching for work. Praying for open doors and financial breakthrough so I can support my siblings and give to the work of God.',
        prayedCount: 31,
        stationId: 'stn_safina_fm',
        stationName: 'Radio Safina',
        countryCode: 'TZ',
        status: 'APPROVED',
        createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      },
      {
        id: 'pray_003',
        authorName: 'Pastor David Kiiza',
        isAnonymous: false,
        category: 'Ministry',
        title: 'Gospel Crusade & Outreach in Rural Shinyanga',
        prayerPoints: 'We are holding a 3-day outdoor Gospel outreach next week. Pray for convicting power of the Holy Spirit, safety for our team, and salvation for hundreds of precious souls.',
        prayedCount: 65,
        stationId: 'stn_upendo_fm',
        stationName: 'Upendo FM 107.7',
        countryCode: 'TZ',
        status: 'APPROVED',
        createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      },
      {
        id: 'pray_004',
        authorName: 'Esther Njeri',
        isAnonymous: false,
        category: 'Family',
        title: 'Restoration & Peace in Our Marriage',
        prayerPoints: 'Asking the saints across East Africa to join in prayer for reconciliation, peace, and understanding in our family.',
        prayedCount: 52,
        stationId: 'stn_hope_fm_kenya',
        stationName: 'Hope FM 93.3',
        countryCode: 'KE',
        status: 'APPROVED',
        createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
      },
      {
        id: 'pray_005',
        authorName: 'Samuel Okello',
        isAnonymous: false,
        category: 'Salvation',
        title: 'Salvation for My University Friends',
        prayerPoints: 'Praying for my classmates at university that God opens their hearts to receive Jesus Christ as their personal Lord and Savior.',
        prayedCount: 29,
        stationId: 'stn_power_fm_ug',
        stationName: 'Power FM 104.1',
        countryCode: 'UG',
        status: 'APPROVED',
        createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
      },
      {
        id: 'pray_006',
        authorName: 'Jean-Paul Habimana',
        isAnonymous: false,
        category: 'Peace',
        title: 'Thanksgiving for God Blessing My New Business',
        prayerPoints: 'Praising God for opening doors to establish an agricultural cooperative in Huye. Praying for wisdom and integrity in leadership.',
        prayedCount: 38,
        stationId: 'stn_maria_rwanda',
        stationName: 'Radio Maria Rwanda 97.3',
        countryCode: 'RW',
        status: 'APPROVED',
        createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      },
      {
        id: 'pray_007',
        authorName: 'Chidinma Eze',
        isAnonymous: false,
        category: 'Guidance',
        title: 'Breakthrough and Freedom from Fear and Insomnia',
        prayerPoints: 'Asking brethren to pray for peaceful sleep and complete freedom from nocturnal fear and anxieties. The Lord is my shield!',
        prayedCount: 44,
        stationId: 'stn_wig_radio_ng',
        stationName: 'WiGRadio Nigeria',
        countryCode: 'NG',
        status: 'APPROVED',
        createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
    ];

    // 14. Station Reviews & Listener Testimonies
    data.stationReviews = [
      {
        id: 'rev_001',
        stationId: 'stn_radio_maria_tz',
        stationSlug: 'radio-maria-tanzania',
        stationName: 'Radio Maria Tanzania',
        authorName: 'Theresia M.',
        rating: 5,
        title: 'A constant source of spiritual nourishment and peace',
        testimony: 'Every morning at 5:00 AM I tune into the Holy Rosary and morning prayers. Radio Maria has transformed my home atmosphere and brought immense calm during difficult seasons.',
        countryCode: 'TZ',
        city: 'Dar es Salaam',
        isApproved: true,
        isFeatured: true,
        createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
      },
      {
        id: 'rev_002',
        stationId: 'stn_safina_fm',
        stationSlug: 'radio-safina-arusha',
        stationName: 'Radio Safina 92.6 FM',
        authorName: 'Baraka Joshua',
        rating: 5,
        title: 'Exceptional teaching sermons and pure worship!',
        testimony: 'Radio Safina provides solid sound biblical teaching. The audio stream quality on Christian Radios is crystal clear without buffering even on mobile data in Arusha.',
        countryCode: 'TZ',
        city: 'Arusha',
        isApproved: true,
        isFeatured: true,
        createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
      },
      {
        id: 'rev_003',
        stationId: 'stn_upendo_fm',
        stationSlug: 'upendo-fm-tanzania',
        stationName: 'Upendo FM 107.7',
        authorName: 'Agnes Christopher',
        rating: 5,
        title: 'Uplifting gospel music that carries me through work',
        testimony: 'I listen to Upendo FM every single workday. The worship segments and live encouragement programs inspire my faith daily. God bless this station!',
        countryCode: 'TZ',
        city: 'Mwanza',
        isApproved: true,
        isFeatured: true,
        createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      },
      {
        id: 'rev_004',
        stationId: 'stn_hope_fm_kenya',
        stationSlug: 'hope-fm-nairobi',
        stationName: 'Hope FM 93.3',
        authorName: 'Kennedy Wanjala',
        rating: 5,
        title: 'Listen from the UK every day!',
        testimony: 'Living in London, Christian Radios lets me stay connected to Kenyan gospel radio with zero lag. Hope FM feels like home.',
        countryCode: 'GB',
        city: 'London',
        isApproved: true,
        isFeatured: true,
        createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'rev_005',
        stationId: 'stn_power_fm_ug',
        stationSlug: 'power-fm-kampala',
        stationName: 'Power FM 104.1',
        authorName: 'Juliet Nakitende',
        rating: 5,
        title: 'Dynamic, modern and deeply rooted in God’s Word',
        testimony: 'Power FM Kampala combines top-notch urban Christian beats with relevant real-life discussions for youth. Truly the best Christian station in Uganda!',
        countryCode: 'UG',
        city: 'Kampala',
        isApproved: true,
        isFeatured: true,
        createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      },
      {
        id: 'rev_006',
        stationId: 'stn_wig_radio_ng',
        stationSlug: 'wig-radio-nigeria',
        stationName: 'WiGRadio Nigeria',
        authorName: 'Oluwaseun Adeleke',
        rating: 5,
        title: 'Spiritual fireworks and life-changing messages',
        testimony: 'The atmosphere on WiGRadio is always charged with divine energy. I listen during my commute across Lagos and feel totally renewed.',
        countryCode: 'NG',
        city: 'Lagos',
        isApproved: true,
        isFeatured: true,
        createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'rev_007',
        stationId: 'stn_klove_us',
        stationSlug: 'k-love-contemporary',
        stationName: 'K-LOVE Radio',
        authorName: 'David Miller',
        rating: 5,
        title: 'Positive, encouraging and beautiful sound',
        testimony: 'K-LOVE has been our family soundtrack for over a decade. Seamless streaming on this portal allows us to listen on all our devices.',
        countryCode: 'US',
        city: 'Dallas',
        isApproved: true,
        isFeatured: true,
        createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
      },
    ];

    // 15. Podcasts & Audio-on-Demand Sermons
    data.podcastEpisodes = [
      {
        id: 'pod_001',
        stationId: 'stn_radio_maria_tz',
        stationName: 'Radio Maria Tanzania',
        stationSlug: 'radio-maria-tanzania',
        title: 'Sala ya Asubuhi na Tafakari ya Neno la Siku',
        description: 'Tafakari ya kina kuhusu Zaburi 23 na jinsi ya kuishi kwa amani katika uongozi wa Mchungaji Mwema.',
        audioUrl: 'https://stream.zeno.fm/f3wvbbqmdg8uv',
        duration: '28:40',
        durationSeconds: 1720,
        preacherName: 'Padre Telesphore Kaberwa',
        publishedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
        category: 'Tafakari & Maombi',
        playCount: 1420,
        artworkUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
      },
      {
        id: 'pod_002',
        stationId: 'stn_safina_fm',
        stationName: 'Radio Safina',
        stationSlug: 'radio-safina-arusha',
        title: 'Kutembea Katika Ushindi wa Imani',
        description: 'Fundisho la nguvu juu ya namna ya kushinda hofu na wasiwasi kupitia Neno lililoandikwa (Waebrania 11:1-6).',
        audioUrl: 'https://stream.zeno.fm/87vkg4w79bhvv',
        duration: '45:15',
        durationSeconds: 2715,
        preacherName: 'Mch. Dkt. Daniel Kavishe',
        publishedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
        category: 'Mafundisho ya Biblia',
        playCount: 2890,
        artworkUrl: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=600&auto=format&fit=crop&q=80',
      },
      {
        id: 'pod_003',
        stationId: 'stn_habari_maalum',
        stationName: 'Habari Maalum FM 97.7',
        stationSlug: 'habari-maalum-arusha',
        title: 'Nguvu ya Shukrani Katika Mazingira Magumu',
        description: 'Mhubiri anachambua jinsi Paulo na Sila walivyomsifu Mungu gerezani na milango ikafunguka (Matendo 16).',
        audioUrl: 'https://stream.zeno.fm/f3wvbbqmdg8uv',
        duration: '35:20',
        durationSeconds: 2120,
        preacherName: 'Evangelist Emmanuel Sulle',
        publishedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
        category: 'Uamsho & Mahubiri',
        playCount: 980,
        artworkUrl: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?w=600&auto=format&fit=crop&q=80',
      },
      {
        id: 'pod_004',
        stationId: 'stn_hope_fm_kenya',
        stationName: 'Hope FM 93.3',
        stationSlug: 'hope-fm-nairobi',
        title: 'Morning Glory Devotion: Overcoming Life Storms',
        description: 'Anchor scriptures from Mark 4:35-41 on the authority of Christ over every wind and turbulent storm in your life.',
        audioUrl: 'https://stream.zeno.fm/87vkg4w79bhvv',
        duration: '22:10',
        durationSeconds: 1330,
        preacherName: 'Pastor Philip Kitoto',
        publishedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
        category: 'Daily Devotional',
        playCount: 1750,
        artworkUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
      },
    ];

    // 16. Daily Scripture Verses
    data.dailyVerses = [
      {
        id: 'verse_today',
        date: new Date().toISOString().split('T')[0],
        reference: 'Isaiah 40:31 / Isaya 40:31',
        textEnglish: '“But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.”',
        textSwahili: '“Bali wao wamngojeao Bwana watapata nguvu mpya; watapanda juu kwa mbawa kama tai; watapiga mbio, wala hawatachoka; watakwenda kwa miguu, wala hawatazimia.”',
        theme: 'Divine Strength & Hope',
        reflection: 'Whatever challenges you face today, wait upon the Lord in prayer and praise. His grace provides renewed vigor and supernatural peace for every journey.',
        audioNarrationUrl: 'https://stream.zeno.fm/f3wvbbqmdg8uv',
      },
      {
        id: 'verse_yesterday',
        date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
        reference: 'Philippians 4:6-7 / Wafilipi 4:6-7',
        textEnglish: '“Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.”',
        textSwahili: '“Msijisumbue kwa neno lo lote; bali katika kila neno kwa kusali na kuomba, pamoja na kushukuru, haja zenu na zijulikane na Mungu. Na amani ya Mungu, ipitayo akili zote, itawahifadhi mioyo yenu na nia zenu katika Kristo Yesu.”',
        theme: 'Peace Over Anxiety',
        reflection: 'Turn every worry into a prayer today. God is in total control of your circumstances.',
        audioNarrationUrl: 'https://stream.zeno.fm/87vkg4w79bhvv',
      },
    ];

    // 17. Seed Donation Campaigns & Giving Infrastructure
    data.donationCampaigns = [
      {
        id: 'camp_001',
        stationId: 'stn_radio_maria_tz',
        stationName: 'Radio Maria Tanzania',
        stationSlug: 'radio-maria-tanzania',
        ownerId: ownerUser1.id,
        title: 'New High-Power FM Transmitter for Mwanza Lake Zone',
        description: 'Help us reach over 3 million unreached souls across Lake Victoria and rural Mwanza with 24/7 Catholic gospel broadcasting and youth evangelization.',
        goalAmount: 15000000,
        currency: 'TZS',
        amountRaised: 8450000,
        supportersCount: 78,
        imageUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&auto=format&fit=crop&q=80',
        startDate: new Date(Date.now() - 30 * 86400000).toISOString(),
        endDate: new Date(Date.now() + 60 * 86400000).toISOString(),
        status: 'ACTIVE',
        createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'camp_002',
        stationId: 'stn_safina_fm',
        stationName: 'Radio Safina 92.6 FM',
        stationSlug: 'radio-safina-arusha',
        ownerId: ownerUser2.id,
        title: 'Solar Power Backup System for Uninterrupted 24/7 Broadcast',
        description: 'Frequent grid power outages cut our signal. A heavy-duty solar inverter array ensures the word of God never goes silent during peak morning prayer hours.',
        goalAmount: 8500000,
        currency: 'TZS',
        amountRaised: 4200000,
        supportersCount: 41,
        imageUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=80',
        startDate: new Date(Date.now() - 20 * 86400000).toISOString(),
        endDate: new Date(Date.now() + 40 * 86400000).toISOString(),
        status: 'ACTIVE',
        createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'camp_003',
        stationId: 'stn_hope_fm_kenya',
        stationName: 'Hope FM 93.3',
        stationSlug: 'hope-fm-nairobi',
        ownerId: ownerUser1.id,
        title: 'Digital High-Definition Audio Studio Modernization',
        description: 'Upgrading analog mixing consoles, Rode broadcast mics, and live studio telephone hybrids to serve millions of listeners with pristine crystal-clear sound.',
        goalAmount: 500000,
        currency: 'KES',
        amountRaised: 310000,
        supportersCount: 52,
        imageUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&auto=format&fit=crop&q=80',
        startDate: new Date(Date.now() - 15 * 86400000).toISOString(),
        endDate: new Date(Date.now() + 45 * 86400000).toISOString(),
        status: 'ACTIVE',
        createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ];

    // Seed Donations
    data.donations = [
      {
        id: 'don_001',
        stationId: 'stn_radio_maria_tz',
        stationName: 'Radio Maria Tanzania',
        ownerId: ownerUser1.id,
        campaignId: 'camp_001',
        campaignTitle: 'New High-Power FM Transmitter for Mwanza Lake Zone',
        donorName: 'Emanuel Mussa',
        isAnonymous: false,
        donorEmail: 'emanuel.mussa@gmail.com',
        donorPhone: '+255713456789',
        amount: 50000,
        grossAmount: 50000,
        platformFeePercentage: 5.0,
        platformFeeAmount: 2500,
        netOwnerAmount: 47500,
        currency: 'TZS',
        fundType: 'GOSPEL_OUTREACH',
        paymentMethod: 'MPESA',
        trackingId: 'DON_TZ_983141',
        status: 'COMPLETED',
        message: 'Keep spreading the light across East Africa!',
        completedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
        createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'don_002',
        stationId: 'stn_safina_fm',
        stationName: 'Radio Safina 92.6 FM',
        ownerId: ownerUser2.id,
        campaignId: 'camp_002',
        campaignTitle: 'Solar Power Backup System for Uninterrupted 24/7 Broadcast',
        donorName: 'Joy Wambui',
        isAnonymous: false,
        donorEmail: 'joy.wambui@yahoo.com',
        donorPhone: '+254722112233',
        amount: 100000,
        grossAmount: 100000,
        platformFeePercentage: 5.0,
        platformFeeAmount: 5000,
        netOwnerAmount: 95000,
        currency: 'TZS',
        fundType: 'TRANSMITTER_FUND',
        paymentMethod: 'TIGO_PESA',
        trackingId: 'DON_TZ_881920',
        status: 'COMPLETED',
        message: 'In support of the new transmitter project.',
        completedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
        createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      },
      {
        id: 'don_003',
        stationId: 'stn_upendo_fm',
        stationName: 'Upendo FM 107.7',
        ownerId: ownerUser1.id,
        donorName: 'Anonymous Listener',
        isAnonymous: true,
        donorEmail: 'bmushi@gmail.com',
        donorPhone: '+255754001122',
        amount: 35000,
        grossAmount: 35000,
        platformFeePercentage: 5.0,
        platformFeeAmount: 1750,
        netOwnerAmount: 33250,
        currency: 'TZS',
        fundType: 'TITHE_OFFERING',
        paymentMethod: 'AIRTEL_MONEY',
        trackingId: 'DON_TZ_776102',
        status: 'COMPLETED',
        message: 'God bless the Lutheran broadcast ministry!',
        completedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
        createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      },
      {
        id: 'don_004',
        stationId: 'stn_hope_fm_kenya',
        stationName: 'Hope FM 93.3',
        ownerId: ownerUser1.id,
        campaignId: 'camp_003',
        campaignTitle: 'Digital High-Definition Audio Studio Modernization',
        donorName: 'Dr. Faith Mutua',
        isAnonymous: false,
        donorEmail: 'faith.mutua@nairobi.ac.ke',
        donorPhone: '+254710998877',
        amount: 60000,
        grossAmount: 60000,
        platformFeePercentage: 5.0,
        platformFeeAmount: 3000,
        netOwnerAmount: 57000,
        currency: 'TZS',
        fundType: 'STUDIO_UPGRADE',
        paymentMethod: 'MPESA',
        trackingId: 'DON_KE_443190',
        status: 'COMPLETED',
        message: 'Supporting the digital studio upgrade in Nairobi.',
        completedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
        createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'don_005',
        stationId: 'stn_radio_maria_tz',
        stationName: 'Radio Maria Tanzania',
        ownerId: ownerUser1.id,
        donorName: 'Sister Grace Mlowe',
        isAnonymous: false,
        donorEmail: 'grace.mlowe@mission.org',
        donorPhone: '+255768223344',
        amount: 150000,
        grossAmount: 150000,
        platformFeePercentage: 5.0,
        platformFeeAmount: 7500,
        netOwnerAmount: 142500,
        currency: 'TZS',
        fundType: 'GENERAL',
        paymentMethod: 'CARD',
        trackingId: 'DON_TZ_559920',
        status: 'COMPLETED',
        message: 'Praying for all the volunteers and evangelists.',
        completedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
        createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
      },
    ];

    // Seed Ledger Entries
    data.ledgerEntries = [
      {
        id: 'ldg_001',
        ownerId: ownerUser1.id,
        stationId: 'stn_radio_maria_tz',
        donationId: 'don_001',
        type: 'DONATION_CREDIT',
        amount: 47500,
        currency: 'TZS',
        balanceAfter: 47500,
        description: 'Net donation credit from Emanuel Mussa (Gross: 50,000 TZS, Fee: 2,500 TZS)',
        createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'ldg_002',
        ownerId: ownerUser1.id,
        stationId: 'stn_radio_maria_tz',
        donationId: 'don_005',
        type: 'DONATION_CREDIT',
        amount: 142500,
        currency: 'TZS',
        balanceAfter: 190000,
        description: 'Net donation credit from Sister Grace Mlowe (Gross: 150,000 TZS, Fee: 7,500 TZS)',
        createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
      },
      {
        id: 'ldg_003',
        ownerId: ownerUser2.id,
        stationId: 'stn_safina_fm',
        donationId: 'don_002',
        type: 'DONATION_CREDIT',
        amount: 95000,
        currency: 'TZS',
        balanceAfter: 95000,
        description: 'Net donation credit from Joy Wambui (Gross: 100,000 TZS, Fee: 5,000 TZS)',
        createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      },
    ];

    // Seed Withdrawal Requests
    data.withdrawalRequests = [
      {
        id: 'wd_001',
        ownerId: ownerUser1.id,
        ownerName: ownerUser1.name,
        ownerEmail: ownerUser1.email,
        stationId: 'stn_radio_maria_tz',
        amount: 80000,
        currency: 'TZS',
        fee: 800,
        netAmount: 79200,
        payoutMethod: 'MPESA',
        payoutAccountName: 'Radio Maria Tanzania Ministry',
        payoutAccountNumber: '+255768223344',
        payoutBankOrProvider: 'Vodacom M-Pesa Tanzania',
        status: 'COMPLETED',
        notes: 'Monthly transmitter fuel & power budget withdrawal',
        adminNotes: 'Approved and disbursed via Vodacom B2C bulk payout.',
        processedBy: 'admin_super',
        requestedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
        processedAt: new Date(Date.now() - 9 * 86400000).toISOString(),
        completedAt: new Date(Date.now() - 9 * 86400000).toISOString(),
      },
    ];

    // 18. Stream Outages
    data.streamOutages = [
      {
        id: 'outage_001',
        stationId: 'stn_radio_maria_tz',
        stationName: 'Radio Maria Tanzania',
        ownerId: ownerUser1.id,
        detectedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
        resolvedAt: new Date(Date.now() - 5 * 86400000 + 4 * 60000).toISOString(),
        status: 'RESOLVED',
        outageDurationMinutes: 4,
        errorReason: 'Shoutcast source reconnect cycle (upstream fiber switch)',
      },
    ];

    console.log('Christian Radios database seeded successfully.');
  });
}
